# Generated by Django 5.1.2 on 2024-10-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='date_pf_publication',
            new_name='date_of_publication',
        ),
    ]
