# Generated by Django 5.1.2 on 2024-10-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('languages', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('other', 'Other')], default='en', max_length=20)),
            ],
        ),
    ]
